- name: Ensure blacklisted homebrew packages are not installed.
  ansible.builtin.homebrew: "name={{ item }} state=absent"
  loop: "{{ homebrew_uninstalled_packages }}"
- name: Ensure configured homebrew packages are installed.
  ansible.builtin.homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ homebrew_installed_packages }}"
  notify:
    - Clear homebrew cache
- name: Upgrade all homebrew packages (if configured).
  ansible.builtin.homebrew: update_homebrew=yes upgrade_all=yes
  when: homebrew_upgrade_all_packages
  notify:
    - Clear homebrew cache
